apiVersion: v1
kind: Secret
metadata:
  name: feathr-online-secret
  namespace: {{ .Release.Name }}
  labels:
    {{- include "feathr-online.labels" . | nindent 4 }}
type: Opaque
stringData:
    FEATHRCI_HOST: 
    FEATHRCI_PASS: 
    FEATHRCI_TABLE: 
    IPGEOLOCATION_APIKEY: 
    CONN_STR: 
    COSMOS_ACCOUNT: 
    COSMOS_API_KEY: 
    COSMOS_DATABASE: 